// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr0xJdJLLMCTR3J7USpqEwCe8z_awqRRQ',
    appId: '1:1027008144971:web:8eb4ca4a69144aba5fcfce',
    messagingSenderId: '1027008144971',
    projectId: 'mypersonalapp1-113cf',
    authDomain: 'mypersonalapp1-113cf.firebaseapp.com',
    databaseURL: 'https://mypersonalapp1-113cf-default-rtdb.firebaseio.com',
    storageBucket: 'mypersonalapp1-113cf.firebasestorage.app',
    measurementId: 'G-MJXECM3KTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa4ldXCE12hcvaQInT7BfmUyRi5eyHMtQ',
    appId: '1:1027008144971:android:5f08cba72d3167885fcfce',
    messagingSenderId: '1027008144971',
    projectId: 'mypersonalapp1-113cf',
    databaseURL: 'https://mypersonalapp1-113cf-default-rtdb.firebaseio.com',
    storageBucket: 'mypersonalapp1-113cf.firebasestorage.app',
  );

}